### ISSUE TITLE
Great tool!

### ISSUE THREAD

**Issue by ghost** [ajkblue/clean-my-mac#1]
Hello,

This bash script is definitely cleaner than the MacPaw CleanMyMac. Thanks you for this small but effective tool

I have a suggestion, what do you think about adding:
https://gist.github.com/pwnsdx/4c9fe2340f258a32e6b2#file-erase-sh-L5
https://gist.github.com/pwnsdx/4c9fe2340f258a32e6b2#file-erase-sh-L6
https://gist.github.com/pwnsdx/4c9fe2340f258a32e6b2#file-erase-sh-L7
as an option "Remove bash history"?

**Comment by ajkblue** [comment]
@pwnsdx I will be implementing these changes soon, but as I was checking for those log files on my machine (which I was very surprised that this much bash history was kept) I found that the file that is referenced on line 5 doesn't exist on my machine at `/var/root/.sh_history`. When I tried to locate that file on my machine, I got this:

```
MBAAJK:~ ajkblue$ sudo ls /var/root/
Password:
.CFUserTextEncoding .forward        Library
MBAAJK:~ ajkblue$ sudo less /var/root/.sh_history
/var/root/.sh_history: No such file or directory
```

What is supposed to be stored in that file?

**Comment by ghost** [comment]
It's because you never executed a command via "sudo su"

**Comment by ajkblue** [comment]
Ohhh, I see, I've never used "sudo su" so I had no log file there. Do you think it is better to add this as part of the [Terminal caches cleaning section on lines 62 to 63](https://github.com/ajkblue/clean-my-mac/blob/master/clean_my_mac.sh#L62-L73) of the script or should it be it's own separate option to remove the bash history?

**Comment by ghost** [comment]
I think it should be better to have its own separate options, some people may not be comfortable to delete their bash history

**Comment by ghost** [comment]
Thanks!
